version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/backend.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  consumer:
    build:
      context: .
      dockerfile: consumer/consumer.Dockerfile
    depends_on:
      - rabbitmq
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: telemetry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/01-create.sql:/docker-entrypoint-initdb.d/init.sql